title:              EthanK-Dev
email:              ethanklocked@gmail.com
description:        ETHAN KIM 개발블로그
author:             ETHAN KIM
baseurl:            ""
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:   
github_username:    EthankLocked
facebook_username:  StartBootstrap
instagram_username:  ethank1232
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           9999
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
highlighter: rouge
